### ISSUE TITLE
Mobile Docs Page X Overflow

### ISSUE THREAD

**Issue by grnnja** [ploomber/ploomber#1022] opened 2022-09-15 20:29 UTC
On docs pages with long words in the title we get overflow which make the page have horizontal scrolling.

galaxy s10:
![image](https://user-images.githubusercontent.com/31556469/190502272-26249f78-2218-47e1-9e10-2aafdeea97aa.png)

I think if remove some padding and maybe decreased the font size on mobile it would fix this.

**Comment by Nekros1712** [comment] 2022-10-19 17:51
heyy @idomic  can you assign this issue to me, would like to work on it

**Comment by idomic** [comment] 2022-10-19 20:04
Sure please submit a PR!

**Comment by edublancas** [comment] 2022-10-24 17:50
I was unable to reproduce this issue, closing it.

**Closed by edublancas** 2022-10-24 17:50 UTC
Labels: bug, hacktoberfest
