### ISSUE TITLE
Enable passing .sql task results to a following .sql task as parameters

### ISSUE THREAD

**Issue by rockraptor5** [ploomber/ploomber#466] opened 2022-01-05 23:17 UTC
Documentation page: community/index

## Use case
I work in a business where we have an abundance of data but not necessarily the best data for data science efforts. In may cases we have millions of time series records for feature building but poor records of the target data we'd like to predict.
Further complicating efforts are our many many different database servers of various type (oracle, sql, teradata, aws, azure). 

Because of this I spend a lot of time helping our business become 'data science ready' by developing data pipelines to build useful datasets. I'm currently using python to integrate and transform disparate data sources and outputting to table 

## Request
I would like to be able to pass unique values from one .sql task to another as parameters. Something like this:
``` yml
tasks:
  - name: get-data-1
    source: sql/first_data.sql
    product: '{{data}}/raw/first_data.parquet'
    client: src.clients.src1
    chunksize: null
  
  - name: get-data-2
    source: sql/second-data.sql
    product: '{{data}}/raw/second-data.parquet'
    client: src.clients.src2
    params:
      startYear: '{{startYear}}'
      endYear: '{{endYear}}'      
    upstream: get-data-1
    chunksize: null
```
second-data-2.sql example
``` sql
select *
from schema.table
where column in (upstream[params])
and year(date) between {{startYear}} and {{endYear}}
```

Alternatively, could I output the params via python as an intermediate .yaml and use as inputs like this?

``` python
import pandas as pd
import yaml

df = pd.read_parquet(upstream['first_data.parquet''])
vals = df['column'].unique()

d = dict({'val':vals})

with open("sample.yaml", "w") as f:
  yaml.dump(d, f)
  f.close()
```

**Comment by edublancas** [comment] 2022-01-06 23:17
Hi @rockraptor5 , thanks a lot for your feedback. I gave it some thought and have the following idea. I think this could solve your problem and related ones.

Currently, tasks support parameters, but users need to explicitly pass a value:

```yaml
tasks:
  - source: query.sql
     product: data.parquet
     params:
       my_param: 42
```

However, we could allow users to define *dynamic parameters* whose value is obtained by executing a function. So you could have something like this:


```yaml
tasks:
    - source: first.sql
      product: first.parquet
   
    - source: second.sql
      product: second.parquet
      params:
        my_param: compute.param
```

```py
import pandas as pd

def param(upstream):
    return pd.read_parquet(upstream["first"]).x.sum()
```

I think this is a clean solution. What do you think?

**Comment by rockraptor5** [comment] 2022-01-07 01:54
@edublancas
That looks great to me; compute.py would be a task b/w first and second.sql?

Thanks for looking into it so quickly! Excited to simplify and streamline my pipeline.

**Comment by rockraptor5** [comment] 2022-01-07 02:14
@edublancas Just thought of something. In my case I'll be pulling a list from python. Something like this:
```python
def param(upstream):
    return pd.read_parquet(upstream["first"]).x.unique()
```
How is that handled in the sql execution? Right now I'm using sqlalchemy which I think passes a tuple into the .sql file. Just want to be sure the end result is:
```sql
where column in ('a','b','c')
```
vs
```sql
where column in [a,b,c]
```

**Comment by reesehopkins** [comment] 2022-01-07 04:52
@edublancas that's very elegant! I confirm what @rockraptor5 noted about params appearing as lists instead of tuples. Is there a way to create a tuple as a parameters?

**Comment by edublancas** [comment] 2022-01-07 13:55
Hi @rockraptor5 and @reesehopkins,

Yes, it's possible to have them as tuples. You could do something like this:

```python
def param(upstream):
    return tuple(pd.read_parquet(upstream["first"]).x.sum())
```

Then in SQL:


```sql
SELECT * FROM TABLE WHERE x in {{my_param}} 
```

Or you may pass a list and have jinja format it:

```sql
SELECT * FROM TABLE WHERE x in ( {{my_param | join(', ') }} )
```

I'll take a stab at this feature, I'll update so you can test it.

**Comment by edublancas** [comment] 2022-01-09 01:43
Alright, I got a POC working. The API is a bit different since there are some implementation details I forgot, but is still pretty much the same.

An example showing a new feature: runtime SQL parameters. See `pipeline.yaml` for details.

To test it, you need to install from git:

```bash
# install from specific branch
pip uninstall ploomber
pip install git+https://github.com/ploomber/ploomber@runtime-params
```

Sample code (see `README.md` for more info):

[sql-runtime-params.zip](https://github.com/ploomber/ploomber/files/7834317/sql-runtime-params.zip)

Let me know if this solves your issue!

**Comment by rockraptor5** [comment] 2022-01-11 21:49
@edublancas I'll check this out later today and report back. Thanks for the quick response!

**Comment by edublancas** [comment] 2022-01-12 16:19
Sure, let me know how it goes!

**Comment by rockraptor5** [comment] 2022-01-13 23:31
@edublancas 
I was able execute the pipeline as is but ran into issues when executing against my own .sql and .py

Observations:
* I successfully executed my own .sql against a local DB when specifying a client in the task. The SQLDump method I don't think will work for this use case because I'm querying multiple clients in the same pipeline.
* When I added a task for functions.compute params against a column in the resulting upstream I get an error with what looks to be the product (see below). 
* functions.py has to be at same level as pipeline.yaml. We tend to organize our source code a bit deeper so it would be nice to be able to specify a path for the referenced function/utility.py

``` python
Building task 'compute_params': 100%|█████████████████████████████████████████| 2/2 [00:00<00:00, 13.81it/s]
Traceback (most recent call last):
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/cli/io.py", line 34, in wrapper
    fn(**kwargs)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/cli/build.py", line 54, in main
    report = dag.build(force=args.force, debug=args.debug)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/dag/dag.py", line 482, in build
    report = callable_()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/dag/dag.py", line 581, in _build
    raise build_exception
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/dag/dag.py", line 514, in _build
    show_progress=show_progress)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 138, in __call__
    raise DAGBuildError(str(exceptions_all))
ploomber.exceptions.DAGBuildError: 
============================================= DAG build failed =============================================
------------------------ PythonCallable: compute_params -> File('out/params.json') -------------------------
- /Users/jramos1/Documents/analytics-projects/sandbox/ploomber-examples/sql-runtime-params/functions.py:7 --
Traceback (most recent call last):
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 186, in catch_exceptions
    fn()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 159, in __call__
    return self.fn(**self.kwargs)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 166, in catch_warnings
    result = fn()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 159, in __call__
    return self.fn(**self.kwargs)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 220, in build_in_subprocess
    report, meta = res.get()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
============================================= Summary (1 task) =============================================
PythonCallable: compute_params -> File('out/params.json')
============================================= DAG build failed =============================================

```

**Comment by edublancas** [comment] 2022-01-18 02:15
Hi,

1. In the sample project that I sent, I specified one global client, however, you can specify task-level clients and it will still work:

```yaml
clients:
  SQLDump: config.get_client

tasks:
  # this uses the global client
  - source: query.sql
    product: out/data.parquet

  - source: functions.compute_params
    product: out/params.json
 
 # this overrides the client
  - source: another.sql 
    product: out/another.parquet
    client: config.override_client
```

2. I'm not following. Can you provide more details? Better if you can you provide some sample code to reproduce the error. 

3. You can nest the pipeline. For example, you may have:

```yaml
  - source: my_module.functions.compute_params
    product: out/params.json
```
Then, create:

```
my_module/
my_module/__init__.py
my_module/functions.py
```
And declare compute params inside  `my_module/functions.py` does this solve the problem?

4. Ploomber automatically inspects your code to determine dependencies:

For example, `another.sql` uses `compute_params` as upstream:

```sql
SELECT *
FROM numbers WHERE x > [[ get_key(upstream["compute_params"], "param") ]]
```

Ploomber parses the code and finds `upstream["compute_params"]` that's how it knows it should run `compute_params` first.

The function `compute_params` depends on the `query` task:

```python
def compute_params(product, upstream):
    df = pd.read_parquet(upstream['query'])
    param = int(df.x.sum())
    Path(product).write_text(json.dumps(dict(param=param)))
```

Ploomber finds the code `upstream['query']` and determines it needs to run `query` first.

**Comment by rockraptor5** [comment] 2022-01-19 21:55
@edublancas 

That's all super helpful. 

3. I was missing the __init__.py

1. I can't send the details for my .sql or the results but I can confirm the first task of the pipeline is successful and creates out/data.parquet. I can also confirm I am able to successfully execute functions.compute_params (util.get_wells in my case) in a notebook and output and generate out/params.json. Still getting an error on the second task where it can't write to the product. Below is my pipeline and dir structure:

```yaml
tasks:
  # dump data
  - name: query
    source: sql/ct3_data.sql
    product: out/data.parquet
    client: src.clients.CT3
    # chunksize: null
  
  # use out/data.parquet, compute a parameter, and store it
  - source: src.util.get_wells
    product: out/params.json
  
  # use out/param.json at runtime to build this query
  # - source: another.sql 
  #   product: out/another.parquet
```
src/util.py
```python
import json
from pathlib import Path
import pandas as pd


def get_wells(product, upstream):
    df = pd.read_parquet(upstream["query"])
    wells = tuple(df["WELL_NAME"].unique())
    Path(product).write_text(json.dumps(dict(well_list=wells)))
```
tree
``` bash
├── README.md
├── __pycache__
│   ├── config.cpython-36.pyc
│   └── functions.cpython-36.pyc
├── config.py
├── input
│   └── data.db
├── out
│   ├── data.parquet
│   └── params.json
├── pipeline.yaml
├── sql
│   └── ct3_data.sql
├── src
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-36.pyc
│   │   ├── __init__.cpython-39.pyc
│   │   ├── clients.cpython-36.pyc
│   │   ├── util.cpython-36.pyc
│   │   └── util.cpython-39.pyc
│   ├── clients.py
│   └── util.py
└── test.ipynb
```
error
```bash
Building task 'get_wells': 100%|█████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.43it/s]
Traceback (most recent call last):
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/cli/io.py", line 34, in wrapper
    fn(**kwargs)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/cli/build.py", line 54, in main
    report = dag.build(force=args.force, debug=args.debug)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/dag/dag.py", line 482, in build
    report = callable_()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/dag/dag.py", line 581, in _build
    raise build_exception
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/dag/dag.py", line 514, in _build
    show_progress=show_progress)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 138, in __call__
    raise DAGBuildError(str(exceptions_all))
ploomber.exceptions.DAGBuildError: 
================================================ DAG build failed =================================================
------------------------------ PythonCallable: get_wells -> File('out/params.json') -------------------------------
----- /Users/jramos1/Documents/analytics-projects/sandbox/ploomber-examples/sql-runtime-params/src/util.py:7 ------
Traceback (most recent call last):
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 186, in catch_exceptions
    fn()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 159, in __call__
    return self.fn(**self.kwargs)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 166, in catch_warnings
    result = fn()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 159, in __call__
    return self.fn(**self.kwargs)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/site-packages/ploomber/executors/serial.py", line 220, in build_in_subprocess
    report, meta = res.get()
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/jramos1/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
================================================ Summary (1 task) =================================================
PythonCallable: get_wells -> File('out/params.json')
================================================ DAG build failed =================================================
```

**Comment by rockraptor5** [comment] 2022-01-20 18:15
@edublancas

I've got it running. This is going to be great!

1. Serial execution worked; i had tried setting the param to an int to simplify the json but that didn't work either.
2. Still having the issue where a tuple isn't properly passed to the query and I get a sql error so I converted my list to a string as a work around. @reesehopkins submitted a similar issue I think.

pipeline.yaml
```yaml
executor:
  dotted_path: ploomber.executors.Serial
  build_in_subprocess: false # do not run function tasks in a subprocess

tasks:
  # dump data
  - name: query
    source: sql/ct3_data.sql
    product: out/data.parquet
    client: src.clients.CT3
    # chunksize: null
  
  # use out/data.parquet, compute a parameter, and store it
  - name: get_wells
    source: src.util.get_wells
    product: out/params.json
  
  # use out/param.json at runtime to build this query
  - name: get_prod
    source: sql/atdb_prod.sql 
    product: out/rates.parquet
    client: src.clients.ATDB
    params:
      min_year: '{{min_year}}'
```
util.py
```python
import json
from pathlib import Path
import pandas as pd


def get_wells(product, upstream):
    df = pd.read_parquet(upstream["query"])
    wells = tuple(df["WELL_NAME"].unique())
    # converting list to string because we're not properly passing the tuple to the query
    wells = "'" + "','".join(wells) + "'"
    Path(product).write_text(json.dumps(dict(well_list=wells)))
```
sql error with tuple input to get_prod
```bash
cx_Oracle.DatabaseError: ORA-00936: missing expression
```

**Comment by edublancas** [comment] 2022-01-25 04:07
Ok, so change the fn to this:

```python
def get_wells(product, upstream):
    df = pd.read_parquet(upstream["query"])
    wells = [f"'{value}'" for value in df["WELL_NAME"].unique()]
    Path(product).write_text(json.dumps(dict(well_list=wells)))
```

Then in your SQL:

```sql
SELECT *
FROM numbers WHERE some_column in ( [[ get_key(upstream["get_wells"], "well_list") | join(", ") ]] )
```

That should render to:

```sql
SELECT *
FROM numbers WHERE some_column in ( 'a', 'b', 'c' )
```

Let me know if that works.

Are there any other pending issues?

**Comment by rockraptor5** [comment] 2022-01-25 19:06
@edublancas 
That works. The list comprehension is cleaner than what I had done to get it working. No other issuse. Thanks!

**Comment by edublancas** [comment] 2022-01-25 19:09
nice! bear in mind that this is a new feature and hasn't been released yet, but you can still use it if you install it from git. I need to work on it a bit more, this will be part of the next release. I'll close this issue when it's out. Thanks a lot for your feedback!

**Comment by edublancas** [comment] 2022-02-02 01:42
Hey @rockraptor5, this is now in the master branch and will be part of the next release! (Coming up this week)

[We're still missing documentation](https://github.com/ploomber/ploomber/issues/519) on this so if you are up for the challenge, we'd appreciate your help! Thanks again for the feedback!

**Closed by edublancas** 2022-02-02 01:42 UTC
