### ISSUE TITLE
CI fails due to an intermitent test

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#847] opened 2022-06-08 21:41 UTC
`tests/products/test_file.py::test_task_with_client_and_metaproduct_isnt_outdated_rtrns_waiting_download[_delete_metadata]`

https://github.com/ploomber/ploomber/runs/6765722111?check_suite_focus=true

**Comment by edublancas** [comment] 2022-06-08 21:55
for context to help whoever works on this:

I tried to debug it about a month ago and couldn't find the issue. I used an Ubuntu docker image to replicate the OS that github action uses (cause this is only failing on Linux, I think) and I couldn't replicate it. I ran the test several times and it never failed.

My guess is that there is some race condition when trying to delete the file, a few months ago we had a similar issue where one test was failing intermittently when deleting a file; after some investigation, I found that there was a race condition when deleting the file, I even found a bug report in the Python forums with the exact same problem! (although that was on Windows).

I ended up changing the function I was using to delete the file and it solved the problem. If I recall correctly, I found out that there are a few functions in Python to delete a file and switching to another one fixed the problem

This has been annoying us for a while. So closing this would be amazing! I think if we cannot find the root cause we may even want to change the implementation (like I did with the windows problem).

**Comment by edublancas** [comment] 2022-06-09 08:03
We've encountered another [similar issue](https://github.com/Wxl19980214/ploomber/runs/6795265787?check_suite_focus=true) (note that this links to a fork and the code hasn't been merged)

What the two examples have in common is that they are both testing the File client logic. When a File client is configured in a pipeline, ploomber will automatically upload all products to remote storage. We support AWS and Google Cloud as backends; however, we also implemented a client with a local backend. The one with the local backend is giving trouble, and I believe is because of the race conditions when accessing the filesystem.

cc @idomic

**Comment by idomic** [comment] 2022-06-23 16:06
@edublancas since we can't really reproduce those locally, we'll change the function used, push the PR and see if the issue persists. Thoughts?

**Comment by edublancas** [comment] 2022-06-23 16:07
what function are you thinking of changing?

**Comment by idomic** [comment] 2022-06-23 16:08
+ @neelasha23 changing it to `remove` instead of `unlink`

**Comment by neelasha23** [comment] 2022-06-29 04:35
yeah it looks like the same error ! Let me check if there's any other way to do it

**Comment by neelasha23** [comment] 2022-06-29 10:04
This is passing again : https://github.com/ploomber/ploomber/actions/runs/2577449460
Doesn't look the issue is with `_delete` or `_edit_source_code`. It's probably happening here

https://github.com/ploomber/ploomber/blob/99d9fcc78502e645b10b91fa2a9ecff5d7a69b45/tests/products/test_file.py#L75

**Comment by Wxl19980214** [comment] 2022-06-29 15:15
I'm testing comment trigger repository dispatch event, please ignore me!

**Closed** 2023-06-21 21:52 UTC
