### ISSUE TITLE
Improving the commander message

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#462] opened 2022-01-03 19:34 UTC
The commander when error occurs should output it to the console, sometimes it isn't clear what's the error

**Comment by edublancas** [comment] 2022-01-04 05:48
I tried to reproduce the error we debugged today but Commander already shows the actual error message (`unknown option --invalid-arg`):

```pytb
In [11]: c.run('python', '--invalid-arg', description='Some description')
====================================== Some description: python --invalid-arg =======================================
unknown option --invalid-arg
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
---------------------------------------------------------------------------
CommanderException                        Traceback (most recent call last)
<ipython-input-11-e9229ad42108> in <module>
----> 1 c.run('python', '--invalid-arg', description='Some description')

~/dev/ploomber/src/ploomber/io/_commander.py in run(self, description, capture_output, expected_output, error_message, hint, show_cmd, *cmd)
    156                 lines.append(f'Hint: {hint}.')
    157
--> 158             raise CommanderException('\n'.join(lines))
    159         else:
    160             return result

CommanderException: An error occurred when executing command: python --invalid-arg
Original error message: Command '('python', '--invalid-arg')' returned non-zero exit status 2.

In [12]:
```

I reviewed the source code and that should be the case, since we're not capturing standard error, so it should be printed out. Maybe we didn't take a look at the whole traceback? Closing this for now since I couldn't reproduce it. But if you can, feel free to re-open.

**Closed by edublancas** 2022-01-04 05:48 UTC
