### ISSUE TITLE
D3 backend  Error

### ISSUE THREAD

**Issue by falcondatalake** [ploomber/ploomber#845] opened 2022-06-08 12:49 UTC
ploomber report --> gives me an error , ValueError: Error when using d3 backend: expected a path with extension .html, but got: '/tmp/tmpmojk06x4.png', please change the extension

**Comment by edublancas** [comment] 2022-06-08 19:05
Adding context for whoever works on this:

In ploomber 0.18.1 we added a D3 backend, which allows users to generate a plot without installing pygraphviz. My guess is that the code called when executing `ploomber report` has a `.png` hardcoded extension, but if we execute this in an environment that does not have pygraphviz installed, it will use D3 and it will fail since D3 produces an HTML plot. A few details to take into account when working on the solution:

`ploomber report` generates an HTML file with a pipeline summary. As part of the process, it calls `DAG.plot()` and embeds it into the HTML file.

With the new D3 backend, we need to ensure that the report correctly displays the plot regardless of which backend was used (D3 or pygraphviz); currently since `ploomber report` does not offer a way to select the backend, the default will be used.


the second step for fixing this is to incorporate a `--plot-backend` argument to `ploomber report` so users can choose which one to use. this involves adding it to the CLI but also adding a new argument to `DAG.to_markup` which is the underlying function that generates the plot

https://github.com/ploomber/ploomber/blob/77d7dbf6b143ee17f886f76b6f3163d0ad5a39c9/src/ploomber/dag/dag.py#L793

**Comment by idomic** [comment] 2022-06-16 22:32
@falcondatalake thanks for reporting this issue!
We pushed a fix and it'll be available from the next release. Keep submitting valuable feedback :)

**Comment by edublancas** [comment] 2022-07-04 11:47
re-opening this since the PR was incomplete:

this fails:

```python
dag.to_markup(backend='d3')
```

```pytb
In [2]: dag.to_markup(backend='d3')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-5d55b4c601dd> in <module>
----> 1 dag.to_markup(backend='d3')

~/dev/ploomber/src/ploomber/dag/dag.py in to_markup(self, path, fmt, sections, backend)
    815             fd, path_to_plot = tempfile.mkstemp(suffix=ext)
    816             os.close(fd)
--> 817             self.plot(output=path_to_plot)
    818             plot_ = image_bytes2html(Path(path_to_plot).read_bytes())
    819         else:

~/dev/ploomber/src/ploomber/dag/dag.py in plot(self, output, include_products, backend)
    911             G = self._to_graph(fmt='pygraphviz',
    912                                include_products=include_products)
--> 913             G.draw(path, prog='dot', args='-Grankdir=LR')
    914
    915             if output == 'embed':

~/miniconda3/envs/ploomber/lib/python3.9/site-packages/pygraphviz/agraph.py in draw(self, path, format, prog, args)
   1594             args = " ".join([args, "-T" + format])
   1595
-> 1596         data = self._run_prog(prog, args)
   1597
   1598         if path is not None:

~/miniconda3/envs/ploomber/lib/python3.9/site-packages/pygraphviz/agraph.py in _run_prog(self, prog, args)
   1385
   1386         if not data:
-> 1387             raise OSError(b"".join(errors).decode(self.encoding))
   1388
   1389         if len(errors) > 0:

OSError: Format: "html" not recognized. Use one of: bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vdx vml vmlz vrml wbmp webp xdot xdot1.2 xdot1.4 xdot_json
```

Even though I'm passing backend d3, it's still trying to use pygraphviz

Also, the `--backend` argument is missing from `ploomber report`

**Comment by 94rain** [comment] 2022-07-07 18:23
I cannot reproduce the error locally (I tried to remove all other arguments to call `dag.to_markup(backend='d3')`).

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/21193371/177842227-b6589ecb-c060-40b0-98d1-65a107aac6f8.png">

I will work on adding `--backend` to `report` first.

**Comment by edublancas** [comment] 2022-07-07 18:26
looks like the problem only arises when you have pygraphviz installed. If I uninstall it, it doesn't break.

to install pygraphviz: https://docs.ploomber.io/en/latest/user-guide/faq_index.html#conda-simplest

**Comment by edublancas** [comment] 2022-07-08 16:53
I realized we're missing tests for `ploomber report`, please add some here https://github.com/ploomber/ploomber/blob/master/tests/cli/test_custom.py

I'll try to reproduce the pygraphviz error, see if i can provide more info. and we'll revisit it once the tests are finished

**Comment by 94rain** [comment] 2022-07-08 21:41
OK, I reproduced the `Format: "html" not recognized` error in the initial report command tests I just wrote.
https://github.com/ploomber/ploomber/runs/7258493669?check_suite_focus=true#step:8:516

However, the `test_to_markup` tests still pass.
https://github.com/ploomber/ploomber/blob/e9938a0caedcd3cf64cea9cbfc3bd9070b62ef1e/tests/dag/test_dag.py#L264-L268

**Comment by edublancas** [comment] 2022-07-08 22:28
Ok, let's use the test that you just wrote as a reference to fix the issue. Then, we'll investigate why `to_markup` isn't raising the same error.

**Comment by 94rain** [comment] 2022-07-11 18:40
Looks like simply adding `backend=backend` to self.plot() will solve the errors I found in `ploomber report` command tests.
https://github.com/ploomber/ploomber/blob/a8ffd62866929ad959c3dbcacd130d202efd3f12/src/ploomber/dag/dag.py#L817
```
self.plot(output=path_to_plot, backend=backend)
```

**Comment by 94rain** [comment] 2022-07-12 14:26
The PR #904 is now ready for review

**Comment by idomic** [comment] 2022-07-19 17:54
This isn't solved yet.

**Comment by edublancas** [comment] 2022-07-19 18:23
i think the problem is that the d3 backend generates a full HTML file, which works fine if we use `ploomber plot`, but if we use`ploomber report` we don't want the full document. but only the HTML tag that embeds the plot. but I'm not sure maybe you're right

**Comment by 94rain** [comment] 2022-07-19 20:15
Two possible directions:
1. extract d3 `<script>`, `<style>` tags from the d3 plot html and insert into the report HTML. This seems to break the markdown style at the moment
2. Use `imgkit`, `Html2Image` or other libraries to convert the d3 plot HTML to image (https://stackoverflow.com/questions/60598837/html-to-image-using-python)

**Comment by edublancas** [comment] 2022-07-19 20:29
adding extra dependencies will complicate setup.

let's go with option 1. i think you can refactor the function that produces the plot so it returns only what you need for the report, and with one argument the full HTML doc.

see if you can modify the script and style so they don't break the report

**Comment by 94rain** [comment] 2022-07-20 16:59
I am able to do the change manually as follows and will think about how to do the following HTML tag manipulation without using additional libraries.
Add the following to `<style>`: (50% scale)
```css
  #dag {
    width: 50%;
    height: 50%;
  }
```
Extract content of `<svg>`from the d3 plot html to `<p>` tag (body.article) in the report


<img width="928" alt="image" src="https://user-images.githubusercontent.com/21193371/180039598-dc374320-2f8c-4285-bfc9-589efd0f48a8.png">

**Comment by edublancas** [comment] 2022-07-20 20:35
Instead of extracting the SVG tag, it's easier if you modify the function that generates the HTML when executing `ploomber plot`:

https://github.com/ploomber/ploomber/blob/54c26e1885c019f4a954d3f4b37ed136cd72a2fc/src/ploomber/dag/plot.py#L60

you can add a parameter like `image_only` that generates the HTML only with the SVG then image_only=True and the full HTML document when image_only=False. We're  using jinja so you can embed that logic inside the HTML template:

https://github.com/ploomber/ploomber/blob/master/src/ploomber/resources/dag_template.html

**Comment by 94rain** [comment] 2022-07-25 18:27
HTML output is now working. However the md output does not seem to work. Has the markdown output ever worked before?

**Comment by 94rain** [comment] 2022-07-25 20:35
In other words, is the following all I need to test manually?
```bash
ploomber report --backend pygraphviz --output report_pygraphviz.html
ploomber report --backend d3 --output report_d3.html

ploomber plot --backend pygraphviz --output plot_pygraphviz.png
ploomber plot --backend pygraphviz --output plot_pygraphviz.html
ploomber plot --backend d3 --output plot_d3.png
ploomber plot --backend d3 --output plot_d3.html
```

**Comment by idomic** [comment] 2022-07-25 23:01
Let me test.
Yes as long as the plots and reports have the right content I don't think we need to cover anything else.

**Closed** 2022-07-26 15:10 UTC
Labels: bug, good first issue, med priority
