### ISSUE TITLE
in-line Uploading log and metrics of pipeline run. 

### ISSUE THREAD

**Issue by JulienR0y** [ploomber/ploomber#768] opened 2022-05-16 12:08 UTC
Friday May 13th: 

Asked in ask-anything channel about if it was possible to upload logfile created during the run to a s3 bucket at the end of a pipeline.yaml run. Within it ( without requiring to upload it manually after).

Command used 
```ploomber build --log info --log-file my.log```

Possible solution until integration is to setup a pipeline.yaml that would upload to the bucket all logfile created or to use in our script logging.Debug("Message"), write to a file during run and upload the file as the last step of the pipeline.yaml file being run.

**Comment by JulienR0y** [comment] 2022-05-16 12:08
[Eduardo](https://app.slack.com/team/U0164GZJ5EK)  [1 day ago](https://ploomber-io.slack.com/archives/C028KJCJDRT/p1652550165367959?thread_ts=1652475182.759139&cid=C028KJCJDRT)
ah. this is an interesting use case. you'd have to add code to manually upload the log file to S3, but since we already support S3 for uploading artifacts. it makes sense to support uploading the log as well. can you create an issue?

**Comment by edublancas** [comment] 2022-05-16 15:45
thanks for your feedback!

**Comment by edublancas** [comment] 2022-09-06 01:58
closing this since it's a duplicate of #897

**Closed by edublancas** 2022-09-06 01:58 UTC
